In [1]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
import seaborn as sb

In [4]:
df = pd.read_excel('Envelope Math.xlsx', sheetname='June')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 46 entries, (nan, Booked Profit, nan, 4216.33, nan, nan) to (nan, Profit, 2818.7, 2421, nan, nan)
Data columns (total 14 columns):
1FF            5 non-null object
Unnamed: 1     0 non-null float64
Unnamed: 2     3 non-null float64
Unnamed: 3     37 non-null object
2FF            40 non-null object
Unnamed: 5     38 non-null object
Unnamed: 6     36 non-null object
Unnamed: 7     24 non-null float64
Unnamed: 8     3 non-null object
Unnamed: 9     0 non-null float64
Unnamed: 10    2 non-null object
Unnamed: 11    1 non-null float64
Unnamed: 12    3 non-null float64
Unnamed: 13    1 non-null float64
dtypes: float64(7), object(7)
memory usage: 5.4+ KB

In [7]:
df.head(50)

                                                                                                  1FF  \
NaN Booked Profit    NaN          4216.33                  NaN            NaN               Occupancy
    Potential Profit NaN          6238.78                  NaN            NaN    Average Nightly Rate
    Date Adjustment  NaN          4393.78                  NaN            NaN    Implied Nightly Rate
    NaN              NaN          NaN                      NaN            NaN                     NaN
                                                                          NaN                     NaN
                                                                          NaN                     NaN
                                                                          NaN                     NaN
    Southport 1FF    NaN          NaN                      NaN            NaN                     NaN
    NaN              157          109.9                    NaN            NaN                     NaN
    Day              Nightly Rate Booked (Y/N)             Sumif          NaN                     NaN
    1                200          Y                        200            0.0                     409
    2                200          Y                        200            0.0                     NaN
    3                250          Y                        250            0.0                     NaN
    4                250          Y                        250            0.0                     NaN
    5                200          Y                        200            0.0                     NaN
    6                200          Y                        200            0.0                     NaN
    7                200          Y                        200            0.0                     NaN
    8                200          N                        0              200.0                   NaN
    9                200          Y                        200            0.0                     NaN
    10               250          Y                        250            0.0                     NaN
    11               250          Y                        250            0.0                     NaN
    12               200          Y                        200            0.0                     NaN
    13               80           N                        0              80.0                    NaN
    14               80           N                        0              80.0                     10
    15               160          Y                        160            0.0                     NaN
    16               195          Y                        195            0.0                     NaN
    17               150          Y                        150            0.0                     NaN
    18               160          Y                        160            0.0                     NaN
    19               105          Y                        105            0.0                     NaN
    20               115          Y                        115            0.0                     NaN
    21               130          Y                        130            0.0                     NaN
    22               130          Y                        130            0.0                     NaN
    23               175          Y                        175            0.0                     NaN
    24               190          Y                        190            0.0                     NaN
    25               50           N                        0              NaN                     NaN
    26               50           Y                        50             NaN                     NaN
    27               65           Y                        65             NaN                     NaN
    28               75           Y                        75             NaN                     NaN
    29               100          Y                        100            NaN                     NaN
    30               100          Y                        100            NaN                     NaN
    NaN              NaN          Sumif revenue not booked Missed Revenue NaN                     NaN
    Revenue          4710         4300                     360            NaN                     NaN
    Rent             1500         1500                     NaN            NaN                     NaN
    Utils            250          250                      NaN            NaN                     NaN
    Airbnb Expense   141.3        129                      NaN            NaN                     NaN
    Profit           2818.7       2421                     NaN            NaN                     NaN

                                                                                 Unnamed: 1  \
NaN Booked Profit    NaN          4216.33                  NaN            NaN           NaN
    Potential Profit NaN          6238.78                  NaN            NaN           NaN
    Date Adjustment  NaN          4393.78                  NaN            NaN           NaN
    NaN              NaN          NaN                      NaN            NaN           NaN
                                                                          NaN           NaN
                                                                          NaN           NaN
                                                                          NaN           NaN
    Southport 1FF    NaN          NaN                      NaN            NaN           NaN
    NaN              157          109.9                    NaN            NaN           NaN
    Day              Nightly Rate Booked (Y/N)             Sumif          NaN           NaN
    1                200          Y                        200            0.0           NaN
    2                200          Y                        200            0.0           NaN
    3                250          Y                        250            0.0           NaN
    4                250          Y                        250            0.0           NaN
    5                200          Y                        200            0.0           NaN
    6                200          Y                        200            0.0           NaN
    7                200          Y                        200            0.0           NaN
    8                200          N                        0              200.0         NaN
    9                200          Y                        200            0.0           NaN
    10               250          Y                        250            0.0           NaN
    11               250          Y                        250            0.0           NaN
    12               200          Y                        200            0.0           NaN
    13               80           N                        0              80.0          NaN
    14               80           N                        0              80.0          NaN
    15               160          Y                        160            0.0           NaN
    16               195          Y                        195            0.0           NaN
    17               150          Y                        150            0.0           NaN
    18               160          Y                        160            0.0           NaN
    19               105          Y                        105            0.0           NaN
    20               115          Y                        115            0.0           NaN
    21               130          Y                        130            0.0           NaN
    22               130          Y                        130            0.0           NaN
    23               175          Y                        175            0.0           NaN
    24               190          Y                        190            0.0           NaN
    25               50           N                        0              NaN           NaN
    26               50           Y                        50             NaN           NaN
    27               65           Y                        65             NaN           NaN
    28               75           Y                        75             NaN           NaN
    29               100          Y                        100            NaN           NaN
    30               100          Y                        100            NaN           NaN
    NaN              NaN          Sumif revenue not booked Missed Revenue NaN           NaN
    Revenue          4710         4300                     360            NaN           NaN
    Rent             1500         1500                     NaN            NaN           NaN
    Utils            250          250                      NaN            NaN           NaN
    Airbnb Expense   141.3        129                      NaN            NaN           NaN
    Profit           2818.7       2421                     NaN            NaN           NaN

                                                                                 Unnamed: 2  \
NaN Booked Profit    NaN          4216.33                  NaN            NaN      0.866667
    Potential Profit NaN          6238.78                  NaN            NaN    157.000000
    Date Adjustment  NaN          4393.78                  NaN            NaN    136.066667
    NaN              NaN          NaN                      NaN            NaN           NaN
                                                                          NaN           NaN
                                                                          NaN           NaN
                                                                          NaN           NaN
    Southport 1FF    NaN          NaN                      NaN            NaN           NaN
    NaN              157          109.9                    NaN            NaN           NaN
    Day              Nightly Rate Booked (Y/N)             Sumif          NaN           NaN
    1                200          Y                        200            0.0           NaN
    2                200          Y                        200            0.0           NaN
    3                250          Y                        250            0.0           NaN
    4                250          Y                        250            0.0           NaN
    5                200          Y                        200            0.0           NaN
    6                200          Y                        200            0.0           NaN
    7                200          Y                        200            0.0           NaN
    8                200          N                        0              200.0         NaN
    9                200          Y                        200            0.0           NaN
    10               250          Y                        250            0.0           NaN
    11               250          Y                        250            0.0           NaN
    12               200          Y                        200            0.0           NaN
    13               80           N                        0              80.0          NaN
    14               80           N                        0              80.0          NaN
    15               160          Y                        160            0.0           NaN
    16               195          Y                        195            0.0           NaN
    17               150          Y                        150            0.0           NaN
    18               160          Y                        160            0.0           NaN
    19               105          Y                        105            0.0           NaN
    20               115          Y                        115            0.0           NaN
    21               130          Y                        130            0.0           NaN
    22               130          Y                        130            0.0           NaN
    23               175          Y                        175            0.0           NaN
    24               190          Y                        190            0.0           NaN
    25               50           N                        0              NaN           NaN
    26               50           Y                        50             NaN           NaN
    27               65           Y                        65             NaN           NaN
    28               75           Y                        75             NaN           NaN
    29               100          Y                        100            NaN           NaN
    30               100          Y                        100            NaN           NaN
    NaN              NaN          Sumif revenue not booked Missed Revenue NaN           NaN
    Revenue          4710         4300                     360            NaN           NaN
    Rent             1500         1500                     NaN            NaN           NaN
    Utils            250          250                      NaN            NaN           NaN
    Airbnb Expense   141.3        129                      NaN            NaN           NaN
    Profit           2818.7       2421                     NaN            NaN           NaN

                                                                                     Unnamed: 3  \
NaN Booked Profit    NaN          4216.33                  NaN            NaN               NaN
    Potential Profit NaN          6238.78                  NaN            NaN               NaN
    Date Adjustment  NaN          4393.78                  NaN            NaN               NaN
    NaN              NaN          NaN                      NaN            NaN               NaN
                                                                          NaN               NaN
                                                                          NaN               NaN
                                                                          NaN               NaN
    Southport 1FF    NaN          NaN                      NaN            NaN     Southport 2FF
    NaN              157          109.9                    NaN            NaN               NaN
    Day              Nightly Rate Booked (Y/N)             Sumif          NaN               Day
    1                200          Y                        200            0.0                 1
    2                200          Y                        200            0.0                 2
    3                250          Y                        250            0.0                 3
    4                250          Y                        250            0.0                 4
    5                200          Y                        200            0.0                 5
    6                200          Y                        200            0.0                 6
    7                200          Y                        200            0.0                 7
    8                200          N                        0              200.0               8
    9                200          Y                        200            0.0                 9
    10               250          Y                        250            0.0                10
    11               250          Y                        250            0.0                11
    12               200          Y                        200            0.0                12
    13               80           N                        0              80.0               13
    14               80           N                        0              80.0               14
    15               160          Y                        160            0.0                15
    16               195          Y                        195            0.0                16
    17               150          Y                        150            0.0                17
    18               160          Y                        160            0.0                18
    19               105          Y                        105            0.0                19
    20               115          Y                        115            0.0                20
    21               130          Y                        130            0.0                21
    22               130          Y                        130            0.0                22
    23               175          Y                        175            0.0                23
    24               190          Y                        190            0.0                24
    25               50           N                        0              NaN                25
    26               50           Y                        50             NaN                26
    27               65           Y                        65             NaN                27
    28               75           Y                        75             NaN                28
    29               100          Y                        100            NaN                29
    30               100          Y                        100            NaN                30
    NaN              NaN          Sumif revenue not booked Missed Revenue NaN               NaN
    Revenue          4710         4300                     360            NaN           Revenue
    Rent             1500         1500                     NaN            NaN              Rent
    Utils            250          250                      NaN            NaN             Utils
    Airbnb Expense   141.3        129                      NaN            NaN    Airbnb Expense
    Profit           2818.7       2421                     NaN            NaN            Profit

                                                                                                  2FF  \
NaN Booked Profit    NaN          4216.33                  NaN            NaN               Occupancy
    Potential Profit NaN          6238.78                  NaN            NaN    Average Nightly Rate
    Date Adjustment  NaN          4393.78                  NaN            NaN    Implied Nightly Rate
    NaN              NaN          NaN                      NaN            NaN                     NaN
                                                                          NaN                     NaN
                                                                          NaN                     NaN
                                                                          NaN                     NaN
    Southport 1FF    NaN          NaN                      NaN            NaN                     NaN
    NaN              157          109.9                    NaN            NaN                 215.467
    Day              Nightly Rate Booked (Y/N)             Sumif          NaN            Nightly Rate
    1                200          Y                        200            0.0                     125
    2                200          Y                        200            0.0                     150
    3                250          Y                        250            0.0                     350
    4                250          Y                        250            0.0                     350
    5                200          Y                        200            0.0                     155
    6                200          Y                        200            0.0                     175
    7                200          Y                        200            0.0                     150
    8                200          N                        0              200.0                   200